# Generated by Django 5.1.4 on 2024-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedisTodoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '待办事项条目表',
                'verbose_name_plural': '待办事项条目表',
                'db_table': 't_api_redis_todo_list_item',
            },
        ),
    ]
